// <auto-generated />
namespace CourseProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _1434te : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1434te));
        
        string IMigrationMetadata.Id
        {
            get { return "202012110835543_1434te"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
